### ISSUE TITLE
error compiling hdf5

### ISSUE THREAD

**Issue by Watchmojo** [IBAMR/autoibamr#102]
autoibamr stopped with the following error:

/usr/bin/ld: ../src/.libs/libhdf5.so: undefined reference to `MPI_Aint_diff'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2216: testhdf5] Error 1
make[1]: Leaving directory '/home/frank/autoibamr/tmp/build/hdf5-1.12.1/test'
make: *** [Makefile:715: all-recursive] Error 1
Failure with exit status: 2
Exit message: There was a problem building hdf5 1.12.1.

Can anyone help? Thank you very much.

**Comment by drwells** [comment]
My best guess is that you are using a version of MPI older than HDF5 can handle - which version of MPI are you using?

**Comment by boyceg** [comment]
Do we need to build HDF5 with MPI support?

**Comment by drwells** [comment]
I don't think so, but autoibamr is set up to use the mpi compiler wrappers for everything.

**Comment by boyceg** [comment]
Are there standard flags for MPI wrappers to extract the "real compilers"? If so, could we just use the "real compilers" to build HDF5 without MPI?

**Comment by drwells** [comment]
I don't think the MPI compiler wrappers have any common flags required by the standard - at least one (the HP MPI implementation) that someone reported on the IBAMR mailing list does not even have `-show`.

**Comment by Watchmojo** [comment]
It seems that my MPI is up-to-date, but the hdf5 to be installed is a relatively old version (1.12.1). 

The problem is solved by changing the first 3 lines in IBAMR-toolchain\packages\hdf5.package into
MAJORVER=1.13
MINORVER=2
CHECKSUM=9c51b3da426977ec622a43dca8adaf4e81eabf838c1ff80c6225ad1d3ed54b5c

**Comment by drwells** [comment]
That should work - I think we can also just disable MPI support inside HDF5 to avoid similar problems.

**Comment by boyceg** [comment]
> I think we can also just disable MPI support inside HDF5

👍

We don't use any MPI features in HDF5 right now, so let's just disable it.

**Comment by drwells** [comment]
Yes - I'll double-check that it still works with our other dependencies (I don't want PETSc to find another copy of HDF5 by accident).

**Comment by drwells** [comment]
@Watchmojo let me know if that fix doesn't work for you.

**Comment by Watchmojo** [comment]
Yes. it works just fine. thanks for the fix.
