### ISSUE TITLE
autoibamr 0.12.1 failure - libmesh with XDR

### ISSUE THREAD

**Issue by NessieCanCode** [IBAMR/autoibamr#114]
Hello,

I'm using autoibamr 0.12.1

getting failure due to libmesh with XDR failure

-- Performing Test LIBMESH_WITH_XDR
-- Performing Test LIBMESH_WITH_XDR - Failed
CMake Error at CMakeLists.txt:811 (MESSAGE):
  IBAMR requires that libMesh be compiled with XDR.

-- Configuring incomplete, errors occurred!
See also "/opt/unmanaged/ibamr/0.12.1/tmp/build/v0.12.1/CMakeFiles/CMakeOutput.log".
See also "/opt/unmanaged/ibamr/0.12.1/tmp/build/v0.12.1/CMakeFiles/CMakeError.log".
Failure with exit status: 1
Exit message: There was a problem configuring ibamr .

Any advise?

**Comment by drwells** [comment]
This is something we should document better. We require that libMesh is built with XDR support - typically this is available (and already installed) through a package named libtirpc or libtirpc-dev. For example, on my arch linux machine, libtirpc is already available (it is needed by the systemd package so it is always available).

Are you able to install packages on this machine? If so, installing one of those two packages should fix the issue.

**Comment by NessieCanCode** [comment]
Thank you for clarifying. I was able to install libtirpc-devel package on RHEL8 that allowed libMesh to be built with XDR.

**Comment by drwells** [comment]
Great!
