### ISSUE TITLE
Cannot debug by GDB when customising examples

### ISSUE THREAD

**Issue by Zhonglu** [IBAMR/autoibamr#116]
Hi,

When I try to debug examples by GDB, I found that I cannot trace back to many source codes.

Is there any fix for this or should I just install the traditional way by using the autoibamr-downloaded packages? 

Autoibamr is very useful and I hope we can also debug by its build.

Appreciate any comment,

Mike

**Comment by drwells** [comment]
This should work. Did you run autoibamr with `--enable-debugging`?

**Comment by Zhonglu** [comment]
Thanks for the prompt reply! Yes, I believe the installation is the debug version with `--enable-debugging`. When I use gdb in the VS code, I can trace back to source code at `tmp/build/petsc-lite-3.17.2/src`, and `tmp/unpack/SAMRAI-2.4.4`, but I can not trace back to the IBAMR relevant source code like `example.cpp`.

**Comment by drwells** [comment]
I'm not sure exactly what caused the problem but it sounds like you fixed it. One possibility for trying to debug a similar issue in the future, when using CMake, is to build your project with
```
make VERBOSE=1
```
to have the generated Makefile print out the commands it runs. You should see `-g` or `-ggdb` (and not `O2` or `O3`) in the call to the C++ compiler.
