### ISSUE TITLE
There was a problem configuring libmesh 1.6.2

### ISSUE THREAD

**Issue by Zhonglu** [IBAMR/autoibamr#117]
Hi,

I got a problem when installing by autoibamr.

Appreciate any hint!

Mike

---------------------------------------------
----- Configuring for optional packages -----
---------------------------------------------
checking for built-in XDR support... no
checking for XDR support in /usr/include/tirpc... yes
checking /home/wei123/ibamr_by_auto/dbg_autoibamr_012/packages/petsc-3.17.5/linux-opt/include/petscversion.h usability... no
checking /home/wei123/ibamr_by_auto/dbg_autoibamr_012/packages/petsc-3.17.5/linux-opt/include/petscversion.h presence... no
checking for /home/wei123/ibamr_by_auto/dbg_autoibamr_012/packages/petsc-3.17.5/linux-opt/include/petscversion.h... no
checking /home/wei123/ibamr_by_auto/dbg_autoibamr_012/packages/petsc-3.17.5/include/petscversion.h usability... no
checking /home/wei123/ibamr_by_auto/dbg_autoibamr_012/packages/petsc-3.17.5/include/petscversion.h presence... no
checking for /home/wei123/ibamr_by_auto/dbg_autoibamr_012/packages/petsc-3.17.5/include/petscversion.h... no
configure: error: *** PETSc was not found, but --enable-petsc-required was specified.
Failure with exit status: 3
Exit message: There was a problem configuring libmesh 1.6.2.

**Comment by Zhonglu** [comment]
Turning of libmesh, rerunning

**Comment by drwells** [comment]
It looks like `PETSC_ARCH` was set to `linux-opt` in your environment - things should work if you unset that variable and run everything again. I'll patch autoibamr in a moment.
