### ISSUE TITLE
enable.sh: No such file or directory

### ISSUE THREAD

**Issue by Lianxiali** [IBAMR/autoibamr#131]
I installed IBAMR by running the script [`autoibamar.sh` ](https://github.com/IBAMR/autoibamr) successfully.  But when trying to follow the instruction section of "Using the installed copy of IBAMR"
`   source ~/autoibamr/packages/configuration/enable.sh`
The error popped up `~/autoibamr/packages/configuration/enable.sh: No such file or directory.`
After checking, '**_enable.sh_**' does not exist in the **_configuration_** folder.

Not sure if this error will affect the use of libraries.

**Comment by drwells** [comment]
Thanks for reporting this - it looks like that file was installed somewhere else. Can you investigate and then put together a patch? Thanks!

**Comment by Lianxiali** [comment]
I just searched the file and found it is located at `autoibamr/configuration`. The script exports the PATHs for each package. 
So, it seems only the file path in the instruction needs to be corrected, i.e. change the script from:

`source ~/autoibamr/packages/configuration/enable.sh`

to 

`source ~/autoibamr/configuration/enable.sh`

**Comment by drwells** [comment]
Want to put together a PR to fix it? 😄

**Comment by Lianxiali** [comment]
Just submitted the PR! 😄

**Comment by drwells** [comment]
Fixed by #132.
