### ISSUE TITLE
 auto compiler  error

### ISSUE THREAD

**Issue by Watchmojo** [IBAMR/autoibamr#72]
Hi, 

autoibamr stopped in the following place. Would you please help?

Thanks 
-----------------------

[  7%] Building CXX object ibtk/src/CMakeFiles/IBTK2d.dir/coarsen_ops/CartSideDoubleRT0Coarsen.cpp.o
[  7%] Building CXX object ibtk/src/CMakeFiles/IBTK2d.dir/coarsen_ops/LMarkerCoarsen.cpp.o
In file included from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/contrib/boost/boost/type_traits/has_bit_and.hpp:43:0,
                 from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/contrib/boost/boost/type_traits.hpp:36,
                 from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/contrib/boost/boost/multi_array.hpp:40,
                 from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/include/ibtk/LNodeIndex.h:31,
                 from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/include/ibtk/LNode.h:23,
                 from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/include/ibtk/LSet.h:24,
                 from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/include/ibtk/LMarkerSet.h:24,
                 from /home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/src/coarsen_ops/LMarkerCoarsen.cpp:17:
/home/fangx/autoibamr/tmp/unpack/IBAMR-0.10.1/ibtk/contrib/boost/boost/type_traits/detail/has_binary_operator.hpp:98:57: fatal error: boost/type_traits/detail/is_likely_lambda.hpp: No such file or directory
 #include <boost/type_traits/detail/is_likely_lambda.hpp>
                                                         ^
compilation terminated.
make[2]: *** [ibtk/src/CMakeFiles/IBTK2d.dir/coarsen_ops/LMarkerCoarsen.cpp.o] Error 1
make[1]: *** [ibtk/src/CMakeFiles/IBTK2d.dir/all] Error 2
make: *** [all] Error 2
Failure with exit status: 2
Exit message: There was a problem building ibamr .

**Comment by drwells** [comment]
This is the same as #68: there are multiple bugs with IBAMR's bundled version of BOOST and older versions of GCC (see also https://github.com/IBAMR/IBAMR/pull/1425 and https://github.com/IBAMR/IBAMR/pull/1439).

Can you switch to using a relatively newer compiler, like GCC 6 or newer?
