### ISSUE TITLE
Manual download of Hypre required

### ISSUE THREAD

**Issue by Zhonglu** [IBAMR/autoibamr#73]
Hi,

I got the following errors. I then tried to manually do the 'git clone https://github.com/hypre-space/hypre /root/autoibamr/tmp/build/petsc-lite-3.13.1/arch-linux-c-opt/externalpackages/git.hypre'. It seems it requires a sudo to execute. Then I rerun the autoibamr.sh then Hypre is installed successfully.

*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Error during download/extract/detection of HYPRE:
Unable to download hypre
Could not execute "['git clone https://github.com/hypre-space/hypre /root/autoibamr/tmp/build/petsc-lite-3.13.1/arch-linux-c-opt/externalpackages/git.hypre']":
Cloning into '/root/autoibamr/tmp/build/petsc-lite-3.13.1/arch-linux-c-opt/externalpackages/git.hypre'...
fatal: unable to access 'https://github.com/hypre-space/hypre/': Failed to connect to github.com port 443: Connection refused
Unable to download package HYPRE from: git://https://github.com/hypre-space/hypre
* If URL specified manually - perhaps there is a typo?
* If your network is disconnected - please reconnect and rerun ./configure
* Or perhaps you have a firewall blocking the download
* You can run with --with-packages-download-dir=/adirectory and ./configure will instruct you what packages to download manually
* or you can download the above URL manually, to /yourselectedlocation
  and use the configure option:
  --download-hypre=/yourselectedlocation
Unable to download package HYPRE from: https://github.com/hypre-space/hypre/archive/93baaa8c9.tar.gz
* If URL specified manually - perhaps there is a typo?
* If your network is disconnected - please reconnect and rerun ./configure
* Or perhaps you have a firewall blocking the download
* You can run with --with-packages-download-dir=/adirectory and ./configure will instruct you what packages to download manually
* or you can download the above URL manually, to /yourselectedlocation/93baaa8c9.tar.gz
  and use the configure option:
  --download-hypre=/yourselectedlocation/93baaa8c9.tar.gz
Unable to download hypre
Could not execute "['git clone https://github.com/hypre-space/hypre /root/autoibamr/tmp/build/petsc-lite-3.13.1/arch-linux-c-opt/externalpackages/git.hypre']":
Cloning into '/root/autoibamr/tmp/build/petsc-lite-3.13.1/arch-linux-c-opt/externalpackages/git.hypre'...
fatal: unable to access 'https://github.com/hypre-space/hypre/': Failed to connect to github.com port 443: Connection refused
Unable to download package HYPRE from: git://https://github.com/hypre-space/hypre
* If URL specified manually - perhaps there is a typo?
* If your network is disconnected - please reconnect and rerun ./configure
* Or perhaps you have a firewall blocking the download
* You can run with --with-packages-download-dir=/adirectory and ./configure will instruct you what packages to download manually
* or you can download the above URL manually, to /yourselectedlocation
  and use the configure option:
  --download-hypre=/yourselectedlocation
*******************************************************************************

Failure with exit status: 1                                                         
Exit message: petsc ./configure failed

**Comment by Zhonglu** [comment]
it seems also necessary to

sudo apt-get install python3-distutils

**Comment by Zhonglu** [comment]
For users in China, it is personally recommended to install Github520 to avoid failure of github connection.

**Comment by Zhonglu** [comment]
I am installing on ubuntu 20.04:
this line required as well
sudo apt install m4

**Comment by Zhonglu** [comment]
it seems better use sudo ./autoibamr.sh and prefix a non-root directory to avoid future trouble!

**Comment by drwells** [comment]
Thanks for letting me know. I will update the readme to include the missing dependencies (we need users to install all the stuff you listed and a few more things).

It would be nice to provide secondary mirrors for some of these libraries but some of our dependencies, like libMesh, are only available through GitHub's CDN. I will document that too.

**Comment by Zhonglu** [comment]
I have successfully installed it by autoibamr, cheers for the authors! Saves good lot of troubles.



> Thanks for letting me know. I will update the readme to include the missing dependencies (we need users to install all the stuff you listed and a few more things).
> 
> It would be nice to provide secondary mirrors for some of these libraries but some of our dependencies, like libMesh, are only available through GitHub's CDN. I will document that too.
