### ISSUE TITLE
How to compile example cases after installation?

### ISSUE THREAD

**Issue by Zhonglu** [IBAMR/autoibamr#74]
Hi,

I have installed the IBAMR successfully by the autoibamr.sh which has been very useful. The authors' efforts are appreciated.

However, I do not understand how to compile the example cases. I tried "make examples" but could not produce the main2d as it used to be. Should I use some commands like "cmake"?

Appreciate any comment.

With kind regards,

Mike

**Comment by Zhonglu** [comment]
Sorry for the noob question.

just **make examples** in **tmp/build/v0.10.1**

**Comment by drwells** [comment]
Yup. autoibamr isn't a great fit for this workflow: see also https://github.com/IBAMR/autoibamr#working-with-ibamr-examples
