### ISSUE TITLE
There was a problem building numdiff 5.9.0.

### ISSUE THREAD

**Issue by hachihh** [IBAMR/autoibamr#98]
I'm building autoibamr on MacOS(12.5.1).

`fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^~~~~~~~~~~
make: *** [flags.o] Error 1
make: *** [analyze.o] Error 1
1 error generated.
make: *** [cmpfns.o] Error 1
1 error generated.
make: *** [arith.o] Error 1
Failure with exit status: 2
Exit message: There was a problem building numdiff 5.9.0.
`

**Comment by drwells** [comment]
Thanks for reporting this - I'll see if I can patch numdiff to get around this.

In the mean time, if you are using homebrew, you should be able to get around this by installing gettext.

**Comment by hachihh** [comment]
Many thanks for the suggestion. I've tried homebrew, and the terminal shows that gettext had been downloaded. I still cannot build it. So I was wondering if there is anything else I could do. 

Regards~

**Comment by drwells** [comment]
I don't know of any other fix but since numdiff is only required by the test suite I patched autoibamr to, by default, not build it. I recommend using the current master branch instead of the last release to fix this issue.

**Comment by hachihh** [comment]
I see...I'll try again. Thanks for you help.
